provider: azure
policy: sync
commonLabels:
  azure.workload.identity/use: "true"
serviceAccount:
  create: true
  name: external-dns
  annotations:
    azure.workload.identity/client-id: ${external_dns_client_id}
  labels:
    azure.workload.identity/use: "true"
podLabels:
  azure.workload.identity/use: "true"
podAnnotations:
  azure.workload.identity/client-id: ${external_dns_client_id}
  azure.workload.identity/tenant-id: ${azure_tenant_id}
azure:
  subscriptionId: ${azure_subscription_id}
  tenantId: ${azure_tenant_id}
  resourceGroup: ${azure_resource_group}
  useWorkloadIdentityExtension: true
extraVolumeMounts:
  - name: azure-config-file
    mountPath: /etc/kubernetes
    readOnly: true
extraVolumes:
  - name: azure-config-file
    secret:
      secretName: azure-config-file