#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: rest-service-cert
#  namespace: prm
#spec:
#  secretName: rest-service-cert
#  issuerRef:
#    name: letsencrypt-staging
#    kind: ClusterIssuer
#  dnsNames:
#    - rest-service.pr-mac.com
#---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: prm
spec:
  secretName: auth-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - auth.pr-mac.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-service-cert
  namespace: prm
spec:
  secretName: postgres-service-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - postgres.pr-mac.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: prometheus
spec:
  secretName: grafana-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - grafana.pr-mac.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: prometheus
spec:
  secretName: prometheus-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - prometheus.pr-mac.com