# Common values
enabled: true

generic-service:
  nameOverride: ui-service

  image:
    repository: ghcr.io/prmac-tech/prm-ui

  ingress:
    host: www.pr-mac.com
    className: nginx
    tlsSecretName: ui-cert

  imagePullSecrets:
    - name: regcred

