# Common values
enabled: true

generic-service:
  nameOverride: rest-service

  image:
    repository: ghcr.io/prmac-tech/rest-service

  ingress:
    host: rest-service.pr-mac.com
    className: nginx
    tlsSecretName: rest-service-cert

  imagePullSecrets:
    - name: regcred

