name: "Create/Amend K8s Cluster"

on:
  workflow_dispatch:
#  push:
#    branches: ['main']
#    paths: ['infrastructure/**']

jobs:
  TerraformApply:
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_docker_password: ${{ secrets.GHCR_SECRET }}
      TF_VAR_postgresql_password: ${{ secrets.POSTGRES_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Terraform init
        working-directory: ./infrastructure
        run: terraform init
#      - name: Terraform unlock
#        working-directory: ./infrastructure
#        run: terraform force-unlock -force 51890e39-111f-53de-3a34-162e0fc7c8ad
      - name: Terraform Plan
        working-directory: ./infrastructure
        run: terraform plan -out "tfplan"
      - name: Terraform Apply
        working-directory: ./infrastructure
        run: terraform apply "tfplan"
